"""
Plant Models for Adaptive Control Simulation
=============================================

Implements nonlinear dynamical systems used as both reference trajectory
generators and unknown plant dynamics f(x, t).

Each plant exposes:
    - f(x, t):       The unknown dynamics vector field
    - x_ref(t):      Reference trajectory at time t
    - x_ref_dot(t):  Time derivative of reference trajectory

Plants:
    - LorenzPlant:    3D chaotic attractor (σ=10, ρ=28, β=8/3)
    - DuffingPlant:   2D nonlinear oscillator with time-varying forcing
    - VanDerPolPlant: 2D limit-cycle oscillator

Mathematical reference: Section 1 of the manuscript.
    ẋ(t) = f(x, t) + u(t)
"""

import numpy as np
from abc import ABC, abstractmethod


class PlantModel(ABC):
    """Abstract base class for nonlinear plant models."""

    def __init__(self, n: int, name: str):
        """
        Parameters
        ----------
        n : int
            State dimension.
        name : str
            Human-readable plant name.
        """
        self.n = n
        self.name = name

    @abstractmethod
    def f(self, x: np.ndarray, t: float) -> np.ndarray:
        """
        Unknown plant dynamics.

        Parameters
        ----------
        x : np.ndarray, shape (n,)
            Current state vector.
        t : float
            Current time.

        Returns
        -------
        np.ndarray, shape (n,)
            Dynamics vector f(x, t).
        """
        pass

    @abstractmethod
    def x_ref(self, t: float) -> np.ndarray:
        """
        Reference trajectory at time t.

        Parameters
        ----------
        t : float
            Current time.

        Returns
        -------
        np.ndarray, shape (n,)
            Reference state xₘ(t).
        """
        pass

    @abstractmethod
    def x_ref_dot(self, t: float) -> np.ndarray:
        """
        Time derivative of reference trajectory.

        Parameters
        ----------
        t : float
            Current time.

        Returns
        -------
        np.ndarray, shape (n,)
            Reference velocity ẋₘ(t).
        """
        pass

    def get_lipschitz_bound(self) -> float:
        """
        Return an estimate of the Lipschitz constant of f(x, t)
        over the compact domain X.

        Returns
        -------
        float
            Estimated Lipschitz bound Lf.
        """
        raise NotImplementedError(
            f"{self.name} does not provide a Lipschitz bound estimate."
        )


class LorenzPlant(PlantModel):
    """
    Lorenz system as both reference generator and plant dynamics.

    The Lorenz system:
        ẋ₁ = σ(x₂ - x₁)
        ẋ₂ = x₁(ρ - x₃) - x₂
        ẋ₃ = x₁x₂ - βx₃

    With standard chaotic parameters σ=10, ρ=28, β=8/3.

    The reference trajectory is generated by pre-integrating the Lorenz
    system from a fixed initial condition. The plant dynamics f(x, t)
    can optionally be a perturbed version (different parameters) to
    stress-test the controller.
    """

    def __init__(self, sigma=10.0, rho=28.0, beta=8.0/3.0,
                 ref_sigma=10.0, ref_rho=28.0, ref_beta=8.0/3.0,
                 ref_x0=None, ref_duration=200.0, ref_dt=1e-4,
                 amplitude_scale=0.05):
        """
        Parameters
        ----------
        sigma, rho, beta : float
            Plant Lorenz parameters (the "unknown" dynamics).
        ref_sigma, ref_rho, ref_beta : float
            Reference trajectory Lorenz parameters.
        ref_x0 : np.ndarray, shape (3,), optional
            Initial condition for reference trajectory.
            Defaults to [1.0, 1.0, 1.0].
        ref_duration : float
            Duration of pre-computed reference trajectory.
        ref_dt : float
            Integration timestep for reference trajectory.
        amplitude_scale : float
            Scale factor to reduce reference amplitude for trackability.
        """
        super().__init__(n=3, name="Lorenz")
        self.sigma = sigma
        self.rho = rho
        self.beta = beta

        self.ref_sigma = ref_sigma
        self.ref_rho = ref_rho
        self.ref_beta = ref_beta
        self.amplitude_scale = amplitude_scale
        self.ref_dt = ref_dt

        if ref_x0 is None:
            ref_x0 = np.array([1.0, 1.0, 1.0])

        # Pre-compute reference trajectory via RK4
        self._ref_times, self._ref_states, self._ref_velocities = \
            self._precompute_reference(ref_x0, ref_duration, ref_dt)

    def _lorenz_rhs(self, x, sigma, rho, beta):
        """Lorenz right-hand side."""
        return np.array([
            sigma * (x[1] - x[0]),
            x[0] * (rho - x[2]) - x[1],
            x[0] * x[1] - beta * x[2]
        ])

    def _precompute_reference(self, x0, duration, dt):
        """Pre-integrate the reference Lorenz system using RK4."""
        n_steps = int(duration / dt)
        times = np.linspace(0, duration, n_steps + 1)
        states = np.zeros((n_steps + 1, 3))
        velocities = np.zeros((n_steps + 1, 3))

        states[0] = x0
        velocities[0] = self._lorenz_rhs(x0, self.ref_sigma,
                                          self.ref_rho, self.ref_beta)

        for i in range(n_steps):
            x = states[i]
            k1 = self._lorenz_rhs(x, self.ref_sigma, self.ref_rho, self.ref_beta)
            k2 = self._lorenz_rhs(x + 0.5*dt*k1, self.ref_sigma,
                                  self.ref_rho, self.ref_beta)
            k3 = self._lorenz_rhs(x + 0.5*dt*k2, self.ref_sigma,
                                  self.ref_rho, self.ref_beta)
            k4 = self._lorenz_rhs(x + dt*k3, self.ref_sigma,
                                  self.ref_rho, self.ref_beta)
            states[i+1] = x + (dt/6.0) * (k1 + 2*k2 + 2*k3 + k4)
            velocities[i+1] = self._lorenz_rhs(states[i+1], self.ref_sigma,
                                               self.ref_rho, self.ref_beta)

        # Apply amplitude scaling
        states *= self.amplitude_scale
        velocities *= self.amplitude_scale

        return times, states, velocities

    def _interpolate_ref(self, t):
        """Linearly interpolate the pre-computed reference at time t."""
        t_clamped = np.clip(t, self._ref_times[0], self._ref_times[-1])
        idx = t_clamped / self.ref_dt
        i = int(np.floor(idx))
        i = min(i, len(self._ref_times) - 2)
        alpha = idx - i
        return i, alpha

    def f(self, x, t):
        """Plant dynamics: Lorenz system (potentially different params)."""
        return self._lorenz_rhs(x, self.sigma, self.rho, self.beta)

    def x_ref(self, t):
        """Reference trajectory from pre-integrated Lorenz system."""
        i, alpha = self._interpolate_ref(t)
        return (1 - alpha) * self._ref_states[i] + alpha * self._ref_states[i+1]

    def x_ref_dot(self, t):
        """Reference velocity from pre-integrated Lorenz system."""
        i, alpha = self._interpolate_ref(t)
        return ((1 - alpha) * self._ref_velocities[i]
                + alpha * self._ref_velocities[i+1])

    def get_lipschitz_bound(self):
        """
        Rough Lipschitz estimate for Lorenz on a bounded domain.
        For |x| < M, the Jacobian norm is bounded by
        max(σ, ρ+M, M+β) approximately.
        """
        M = 50.0  # typical Lorenz attractor bound
        return max(self.sigma, self.rho + M, M + self.beta)


class DuffingPlant(PlantModel):
    """
    Duffing oscillator with time-varying forcing.

    Written as a first-order system:
        ẋ₁ = x₂
        ẋ₂ = -δx₂ - α(t)x₁ - βx₁³ + γcos(ωt)

    where α(t) = α₀ + Δα·sin(ω_drift·t) introduces non-autonomous drift,
    stressing the IFT velocity bounds of the ideal parameters.
    """

    def __init__(self, delta=0.3, alpha0=1.0, beta_coeff=1.0,
                 gamma=0.5, omega=1.2,
                 delta_alpha=0.2, omega_drift=0.1,
                 ref_amplitude=1.0, ref_omega=0.5):
        """
        Parameters
        ----------
        delta : float
            Damping coefficient.
        alpha0 : float
            Base linear stiffness.
        beta_coeff : float
            Cubic stiffness coefficient.
        gamma : float
            Forcing amplitude.
        omega : float
            Forcing frequency.
        delta_alpha : float
            Amplitude of time-varying stiffness perturbation.
        omega_drift : float
            Frequency of stiffness drift.
        ref_amplitude, ref_omega : float
            Simple sinusoidal reference trajectory parameters.
        """
        super().__init__(n=2, name="Duffing")
        self.delta = delta
        self.alpha0 = alpha0
        self.beta_coeff = beta_coeff
        self.gamma = gamma
        self.omega = omega
        self.delta_alpha = delta_alpha
        self.omega_drift = omega_drift
        self.ref_amplitude = ref_amplitude
        self.ref_omega = ref_omega

    def _alpha(self, t):
        """Time-varying stiffness parameter."""
        return self.alpha0 + self.delta_alpha * np.sin(self.omega_drift * t)

    def f(self, x, t):
        """Duffing oscillator dynamics."""
        alpha_t = self._alpha(t)
        return np.array([
            x[1],
            -self.delta * x[1] - alpha_t * x[0]
            - self.beta_coeff * x[0]**3
            + self.gamma * np.cos(self.omega * t)
        ])

    def x_ref(self, t):
        """Simple sinusoidal reference trajectory."""
        A, w = self.ref_amplitude, self.ref_omega
        return np.array([
            A * np.sin(w * t),
            A * w * np.cos(w * t)
        ])

    def x_ref_dot(self, t):
        """Reference trajectory derivative."""
        A, w = self.ref_amplitude, self.ref_omega
        return np.array([
            A * w * np.cos(w * t),
            -A * w**2 * np.sin(w * t)
        ])

    def get_lipschitz_bound(self):
        M = 5.0  # assumed state bound
        alpha_max = self.alpha0 + abs(self.delta_alpha)
        return max(1.0, self.delta + alpha_max + 3 * self.beta_coeff * M**2)


class VanDerPolPlant(PlantModel):
    """
    Van der Pol oscillator.

    First-order system:
        ẋ₁ = x₂
        ẋ₂ = μ(1 - x₁²)x₂ - x₁

    Exhibits a stable limit cycle for μ > 0. Smooth and bounded,
    providing a controlled-difficulty benchmark.
    """

    def __init__(self, mu=1.0, ref_amplitude=0.5, ref_omega=1.0):
        """
        Parameters
        ----------
        mu : float
            Nonlinearity parameter. Larger μ → more nonlinear.
        ref_amplitude, ref_omega : float
            Sinusoidal reference trajectory parameters.
        """
        super().__init__(n=2, name="VanDerPol")
        self.mu = mu
        self.ref_amplitude = ref_amplitude
        self.ref_omega = ref_omega

    def f(self, x, t):
        """Van der Pol dynamics."""
        return np.array([
            x[1],
            self.mu * (1 - x[0]**2) * x[1] - x[0]
        ])

    def x_ref(self, t):
        """Simple sinusoidal reference."""
        A, w = self.ref_amplitude, self.ref_omega
        return np.array([
            A * np.sin(w * t),
            A * w * np.cos(w * t)
        ])

    def x_ref_dot(self, t):
        """Reference trajectory derivative."""
        A, w = self.ref_amplitude, self.ref_omega
        return np.array([
            A * w * np.cos(w * t),
            -A * w**2 * np.sin(w * t)
        ])

    def get_lipschitz_bound(self):
        M = 4.0  # limit cycle bound
        return max(1.0, self.mu * (1 + M**2) + 1)
